# @package _global_

defaults:
  - default.yaml

augmentation:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.RandomResizedCrop
      size: 448       
      scale:
        - 0.4
        - 1.0

    - _target_: torchvision.transforms.v2.RandomApply
      p: 0.8
      transforms:
        - _target_: torchvision.transforms.v2.ColorJitter
          brightness: 0.32
          contrast: 0.32
          saturation: 0.32
          hue: 0.08

    - _target_: torchvision.transforms.v2.RandomGrayscale
      p: 0.2