_target_: transformers.TrainingArguments
output_dir: ${paths.output_dir}
# overwrite_output_dir: true

do_train: true
do_eval: true

num_train_epochs: 20

# If set to a positive number, the total number of training steps to perform. 
# Overrides num_train_epochs.
max_steps: -1 

bf16: false
fp16: false
# tf32: true  # only for ampere arch

per_device_train_batch_size: 16
per_device_eval_batch_size: 16

gradient_accumulation_steps: 1

dataloader_num_workers: 4
dataloader_pin_memory: true
dataloader_persistent_workers: true

learning_rate: 1e-4
lr_scheduler_type: cosine
warmup_steps: 1000
weight_decay: 1e-2
max_grad_norm: 1.0

metric_for_best_model: eval_recall
greater_is_better: true
load_best_model_at_end: true

eval_strategy: epoch
eval_steps: 1

save_strategy: epoch
save_total_limit: 2
save_only_model: true
save_on_each_node: true # only if multi-node training

logging_strategy: epoch
logging_steps: 1

hub_strategy: checkpoint

# -- important do not touch! -- 
remove_unused_columns: false 
eval_do_concat_batches: true
# -- end of do not touch! -- 

ddp_find_unused_parameters: false

include_for_metrics: ['loss']
auto_find_batch_size: false

# Reproducibility
seed: 42
data_seed: 42