# @package _global_

defaults:
  - default_clip.yaml

model:
  _args_:
    - EVA02-L-14
    - merged2b_s4b_b131k
    - hf-hub:project-oceania/CLIP-EVA02-L-14.planktonzilla-pt-best_loss-512

img_size: 224
freeze_backbone: false