# @package _global_

defaults:
  - default.yaml

model:
  _args_:
    - eva02_large_patch14_448.mim_m38m_ft_in22k_in1k

image_processor:
  _args_:
    - eva02_large_patch14_448.mim_m38m_ft_in22k_in1k
