defaults:
  - default.yaml

name: project-oceania/zoolake-taxo

transform:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.ToTensor
    # the actual sizes are set at training time depending on the model
    - _target_: torchvision.transforms.v2.Resize
      size:
        - ${img_size}
        - ${img_size}
      antialias: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.054, 0.050, 0.045]
      std: [0.15172781102261, 0.141, 0.125]