defaults:
  - default.yaml

name: project-oceania/zoolake

transform:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.ToTensor
    # the actual sizes are set at training time depending on the model
    - _target_: torchvision.transforms.v2.Resize
      size:
        - ${img_size}
        - ${img_size}
      antialias: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.0692, 0.0638, 0.0564]
      std: [0.1633, 0.1521, 0.334]