defaults:
  - default.yaml

name: project-oceania/zooscannet-taxo

transform:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.ToTensor
    # the actual sizes are set at training time depending on the model
    - _target_: torchvision.transforms.v2.Resize
      size:
        - ${img_size}
        - ${img_size}
      antialias: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.9289, 0.9289, 0.9289]
      std: [0.161, 0.161, 0.161]