defaults:
  - default.yaml

name: project-oceania/zooscannet

transform:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.ToTensor
    # the actual sizes are set at training time depending on the model
    - _target_: torchvision.transforms.v2.Resize
      size:
        - ${img_size}
        - ${img_size}
      antialias: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.996, 0.989, 0.981]
      std: [0.127, 0.023, 0.035]