defaults:
  - default.yaml

_target_: planktonzilla.dataset_import.dataset_importer.LenslessDatasetImporter
hf_dataset_name: lensless
push_to_hub: true
human_readable_name: Lensless Freshwater Plankton Dataset
description: A mixture of ten freshwater plankton species imaged with a lensless microscope designed for in situ data collection.
source_url: https://ibm.ent.box.com/v/PlanktonData
license: cc-by-4.0
citation_apa: |
  Pastore, V. P., Zimmerman, T. G., Biswas, S. K., & Bianco, S. (2020). Annotation-free learning of 
  plankton for classification and anomaly detection. Scientific Reports, 10(1), 12142. https://doi.org/10.1038/s41598-020-68662-3

citation_bibtex: |
  @article{dataset:lensless,
    title     = {Annotation-free learning of plankton for classification and anomaly detection},
    author    = {Pastore, V.P. and Zimmerman, T.G. and Biswas, S.K. and Bianco, S.},
    journal   = {Scientific Reports},
    volume    = {10},
    number    = {1},
    pages     = {12142},
    year      = {2020},
    publisher = {Nature Publishing Group},
    doi       = {10.1038/s41598-020-68662-3},
    url       = {https://doi.org/10.1038/s41598-020-68662-3}
  }