defaults:
  - default.yaml

_target_: planktonzilla.dataset_import.dataset_importer.PlanktoScopeDatasetImporter
hf_dataset_name: planktoscope
push_to_hub: true

human_readable_name: "PlanktoScope_reference : plankton images captured with the PlanktoScope"
license: "cc-by-nc-4.0"
description: |
  Plankton was imaged with the PlanktoScope in different oceanic regions using different nets and protocol of 
  conservation. This dataset aims to serve as reference for taxonomic identification with the PlanktoScope 
  across 256 plankton taxa from 20µm to 300µm. Reference dataset can also serve as learning set for prediction 
  in Ecotaxa (https://ecotaxa.obs-vlfr.fr/prj/15535). 

  The full images were processed and segmented with the PlanktoScope around each individual. A set of associated 
  features were measured on the objects with skimage.measure. All objects were classified into 256 different 
  classes using the web application EcoTaxa (http://ecotaxa.obs-vlfr.fr). The following dataset corresponds to 
  the 169, 149 objects and their calculated features. The different files provide information about the features 
  of the objects, their taxonomic identification as well as the raw images.
  
download_uris: "https://www.seanoe.org/data/00989/110078/data/124113.tar"
source_url: "https://www.seanoe.org/data/00989/110078/"
paperswithcode_id: "planktoscope"
citation_apa: |
  Zaccomer Hugo, Biteye Amadou, Caudan Corentin, Finet Thomas, Leblanc Karine, Le Bris Caroline, Le Gall Florence, 
  Legeay Erwan, Marques Virginie, Moirand Laurine, Oddone Anna, Persat Romain, Portefin Emilie, Rigaut-Jalabert Fabienne, 
  Thueux Manon, de Vargas Colomban, Vigneron Mathilde, Vogt Meike, Weymiens Lucien, Lombard Fabien (2025). 
  PlanktoScope_reference : plankton images captured with the PlanktoScope. SEANOE. https://doi.org/10.17882/110078

citation_bibtex: |
  @article{dataset:planktoscope,
    title      = {PlanktoScope_reference : plankton images captured with the PlanktoScope},
    author     = {Zaccomer, Hugo and Biteye, Amadou and Caudan, Corentin and Finet, 
                  Thomas and Leblanc, Karine and Le Bris, Caroline and Le Gall, 
                  Florence and Legeay, Erwan and Marques, Virginie and Moirand, 
                  Laurine and Oddone, Anna and Persat, Romain and Portefin, Emilie 
                  and Rigaut-Jalabert, Fabienne and Thueux, Manon and de Vargas, 
                  Colomban and Vigneron, Mathilde and Vogt, Meike and Weymiens, 
                  Lucien and Lombard, Fabien},
    year       = 2025,
    journal    = {SEANOE},
    doi        = {10.17882/110078},
    affiliation = {CNRS, Laboratoire d'Océanographie de Villefranche (LOV), Sorbonne Université, Villefranche-sur-Mer, France.
    IRD, Univ Brest, Ifremer, CNRS, LEMAR, 29280, Plouzané, France. Volontaire Officier Aspirant de la Marine Nationale, France.
    Institut de l'Océan de l'Alliance Sorbonne Université, Sorbonne Université, 75005 Paris, France. School of Environmental 
    Sciences, University of East Anglia, Norwich, NR4 7TJ, UK. Aix-Marseille Université, Université de Toulon, CNRS, IRD, MIO 
    UM110, Marseille, France. Sorbonne Université, CNRS, UMR7144 AD2M, ECOMAP, Station Biologique de Roscoff, 29680 Roscoff, France.
    Unit of Land Change Science, Swiss Federal Research Institute WSL, Birmensdorf, Switzerland. Ecosystem and Landscape Evolution, 
    Institute of Terrestrial Ecosystems, Department of Environmental Systems Science, ETH Zürich, Zurich, Switzerland. Plankton 
    Planet Non-Governmental Organization (NGO), Station Biologique de Roscoff, 29680 Roscoff, France. Sorbonne Université, CNRS, 
    FR2424, Station Biologique de Roscoff, 29680 Roscoff, France. Sorbonne Université, CNRS, Laboratoire d'Écogéochimie des 
    Environnements Benthiques (LECOB), Observatoire Océanologique de Banyuls, France. Research Federation for the study of Global 
    Ocean Systems Ecology and Evolution, FR2022 Tara GOSEE, F-75016 Paris, France. MARBEC, Univ Montpellier, CNRS, Ifremer, IRD,
    Montpellier, France. Environmental Physics, Institute of Biogeochemistry and Pollutant Dynamics, ETH Zürich, 8092 Zürich, Switzerland.}
  }

  